name: Discord Notification

on:
  push:
    branches:
      - "*"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        run: |
          TIMESTAMP=$(date +"%d/%m/%Y %H:%M:%S")

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"🚀 Commit mới\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nUser: ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}\nTime: $TIMESTAMP\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
